### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by brisingraerowing** [ZornTaov/BedcraftAndBeyond#8]
After following the instructions on the CurseForge page to fix a crash with Forestry in 1.9.4, I get the following crash on startup:

``` text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.9.4-v1.jar)
  FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  BCModPlugin (zz-backpacks 1.9.4 - 3.1.0.jar)
  CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.7.jar)
  DLFMLCorePlugin (DynamicLights-1.9.4.jar)
  LoadingPlugin (Quark-beta-28.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  TNTUtilities Core (tnt_utilities-mc1.9.4-1.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/21/16 9:11 PM
XRay version: 26
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at zornco.bedcraftbeyond.frames.FrameLoader.addToFramesFromStream(FrameLoader.java:75)
    at zornco.bedcraftbeyond.frames.FrameLoader.tryFrameTypeFileLoad(FrameLoader.java:149)
    at zornco.bedcraftbeyond.frames.FrameLoader.compileFrames(FrameLoader.java:166)
    at zornco.bedcraftbeyond.BedCraftBeyond.postInit(BedCraftBeyond.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:772)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
--------------- SNIP ------------
```

**Comment by robotgryphon** [comment]
Please also post your wood.json file here?

**Comment by brisingraerowing** [comment]
``` json
{ "key": "forestry:planks.fireproof.1", "blacklist": ["0-15"] }
```

Same as the [post on CurseForge](http://minecraft.curseforge.com/projects/bed-craft-and-beyond?comment=17).

**Comment by robotgryphon** [comment]
Ah, this was why I linked the full doc. See the example file I linked - you need to match that format. The crash was a parsing fail (which we'll fix now)

**Comment by robotgryphon** [comment]
https://github.com/ZornTaov/BedcraftAndBeyond/blob/1.9.4/docs/example-wood.json

**Comment by robotgryphon** [comment]
Do you still receive a crash (with or without the fix) on version 2.3.3?

**Comment by brisingraerowing** [comment]
I'll have to check. Not able to play MC ATM, due to strange OpenGL errors.

**Comment by robotgryphon** [comment]
After tinkering quite a bit and using frame files (with and without blacklisting Forestry) the frames seem to behave. This issue lies on forestry's end now. Closing.
